// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK3--IBrsSAe48VSgwGDeOcvFqNpy23-M',
    appId: '1:760961413610:web:a090ac6741154462d4c293',
    messagingSenderId: '760961413610',
    projectId: 'swaransh-academy',
    authDomain: 'swaransh-academy.firebaseapp.com',
    storageBucket: 'swaransh-academy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC994stPhjVqZ0xBzZJ90U1HTYdFaw7mKA',
    appId: '1:760961413610:android:45085df68e5924edd4c293',
    messagingSenderId: '760961413610',
    projectId: 'swaransh-academy',
    storageBucket: 'swaransh-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9dt9bPNvJ_GAjalVDCKbtsC5Y-Wz1_C0',
    appId: '1:760961413610:ios:05468a8261f1e672d4c293',
    messagingSenderId: '760961413610',
    projectId: 'swaransh-academy',
    storageBucket: 'swaransh-academy.firebasestorage.app',
    iosBundleId: 'com.example.flutterStarterTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9dt9bPNvJ_GAjalVDCKbtsC5Y-Wz1_C0',
    appId: '1:760961413610:ios:05468a8261f1e672d4c293',
    messagingSenderId: '760961413610',
    projectId: 'swaransh-academy',
    storageBucket: 'swaransh-academy.firebasestorage.app',
    iosBundleId: 'com.example.flutterStarterTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK3--IBrsSAe48VSgwGDeOcvFqNpy23-M',
    appId: '1:760961413610:web:dc50c76017e9a21ad4c293',
    messagingSenderId: '760961413610',
    projectId: 'swaransh-academy',
    authDomain: 'swaransh-academy.firebaseapp.com',
    storageBucket: 'swaransh-academy.firebasestorage.app',
  );
}
