# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-06-30T16:24:15+00:00

from __future__ import annotations

from datetime import date
from typing import List, Optional, Union

from app.core.db import get_db
from app.core.enums import AdmissionType, Batch, Department, FeeType, LearningMode
from app.features.student import service
from app.features.student.model import (
    StudentBasic,
    StudentCreate,
    StudentFull,
    StudentUpdate,
)
from fastapi import APIRouter, Depends

router = APIRouter(tags=['Students'])


@router.post('/student', response_model=StudentFull, tags=['Students'])
async def post_student(body: StudentCreate, db=Depends(get_db)) -> StudentFull:
    """
    Create Student (manual, admin-only)
    """
    student_data = body.model_dump(mode='python')
    return await service.create_student(student_data, db)


@router.get(
    '/student/{id}', response_model=Union[StudentFull, StudentBasic], tags=['Students']
)
async def get_student_id(id: int, db=Depends(get_db)) -> Union[StudentFull, StudentBasic]:
    """
    Get Student
    """
    return await service.get_student(id, db)


@router.put('/student/{id}', response_model=StudentFull, tags=['Students'])
async def put_student_id(id: int, body: StudentUpdate = ..., db=Depends(get_db)) -> StudentFull:
    """
    Update Student
    """
    return await service.update_student(id, body, db)


@router.delete('/student/{id}', response_model=None, tags=['Students'])
async def delete_student_id(id: int, db=Depends(get_db)) -> None:
    """
    Delete Student
    """
    await service.delete_student(id, db)


@router.get(
    '/studentList',
    response_model=List[Union[StudentFull, StudentBasic]],
    tags=['Students'],
)
async def get_student_list(
    department: Optional[Department] = None,
    admission_type: Optional[AdmissionType] = None,
    learning_mode: Optional[LearningMode] = None,
    fee_type: Optional[FeeType] = None,
    batch: Optional[Batch] = None,
    fees_min: Optional[float] = None,
    fees_max: Optional[float] = None,
    joined_after: Optional[date] = None,
    joined_before: Optional[date] = None,
    search: Optional[str] = None,
    db=Depends(get_db),
) -> List[Union[StudentFull, StudentBasic]]:
    """
    Get Students List
    """
    return await service.get_students_list(
        db,
        department=department,
        admission_type=admission_type,
        learning_mode=learning_mode,
        fee_type=fee_type,
        batch=batch,
        fees_min=fees_min,
        fees_max=fees_max,
        joined_after=joined_after,
        joined_before=joined_before,
        search=search,
    )

