# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-06-30T16:24:15+00:00

from __future__ import annotations

from datetime import date

from app.core.auth.auth import get_current_user
from app.core.db import get_db
from app.core.enums import AdmissionType, Batch, Department, FeeType, LearningMode
from app.features.student import service
from app.features.student.model import (
    StudentCreate,
    StudentFullRead,
    StudentUpdate,
)
from fastapi import APIRouter, Depends

router = APIRouter(tags=['Students'])


@router.post('/student', response_model=StudentFullRead, tags=['Students'])
async def post_student(body: StudentCreate, db=Depends(get_db), user = Depends(get_current_user)) -> StudentFullRead:
    """
    Create Student (manual, admin-only)
    """
    student_data = body.model_dump(mode='python')
    return await service.create_student(student_data, db)


@router.get(
    '/student/{id}', response_model=StudentFullRead, tags=['Students']
)
async def get_student_id(id: int, db=Depends(get_db),user = Depends(get_current_user)) -> StudentFullRead:
    """
    Get Student
    """
    return await service.get_student(id, db)


@router.put('/student/{id}', response_model=StudentFullRead, tags=['Students'])
async def put_student_id(id: int, body: StudentUpdate = ..., db=Depends(get_db), user = Depends(get_current_user))-> StudentFullRead:
    """
    Update Student
    """
    print("STUDENT UPDATE MODEL RECIVED IN ROUTER:\n", body)
    return await service.update_student(id, body, db)


@router.delete('/student/{id}', response_model=None, tags=['Students'])
async def delete_student_id(id: int, db=Depends(get_db), user = Depends(get_current_user)) -> None:
    """
    Delete Student
    """
    await service.delete_student(id, db)


@router.get(
    '/studentList',
    response_model=list[StudentFullRead],
    tags=['Students'],
)
async def get_student_list(
    department: Department | None = None,
    admission_type: AdmissionType | None = None,
    learning_mode: LearningMode | None = None,
    fee_type: FeeType | None = None,
    batch: Batch | None = None,
    fees_min: float | None = None,
    fees_max: float | None = None,
    joined_after: date | None = None,
    joined_before: date | None = None,
    search: str | None = None,
    db=Depends(get_db),
    user = Depends(get_current_user)
) -> list[StudentFullRead]:
    """
    Get Students List
    """
    return await service.get_students_list(
        db,
        department=department,
        admission_type=admission_type,
        learning_mode=learning_mode,
        fee_type=fee_type,
        batch=batch,
        fees_min=fees_min,
        fees_max=fees_max,
        joined_after=joined_after,
        joined_before=joined_before,
        search=search,
    )

