# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-06-30T16:24:15+00:00

from __future__ import annotations

from fastapi import APIRouter

from ..dependencies import *

router = APIRouter(tags=['Users'])


@router.post('/user', response_model=User, tags=['Users'])
def post_user(body: UserCreate) -> User:
    """
    Create/Sync User Profile + Resolve Role
    """
    pass


@router.get('/user/{id}', response_model=User, tags=['Users'])
def get_user_id(id: UUID) -> User:
    """
    Get User By ID
    """
    pass
