# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-06-30T16:24:15+00:00

from datetime import date
from typing import List, Optional, Union
from uuid import UUID

from .models import (
    AdmissionForm,
    AdmissionFormCreate,
    AdmissionStatus,
    AdmissionType,
    AssistanceQuery,
    Batch,
    Course,
    CourseCreate,
    Department,
    FeeType,
    LearningMode,
    Payment,
    PaymentCreate,
    StudentBasic,
    StudentCreate,
    StudentFull,
    StudentUpdate,
    User,
    UserCreate,
)
