# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-06-30T16:24:15+00:00

from __future__ import annotations

from app.core.auth.auth import get_current_user
from app.core.db import get_db
from app.features.payment import service
from app.features.payment.model import Payment, PaymentCreate
from fastapi import APIRouter, Depends

router = APIRouter(tags=['Payments'])


@router.post('/student/{id}/payment', response_model=Payment, tags=['Payments'])
async def post_student_id_payment(id: int, body: PaymentCreate = ..., db=Depends(get_db), user = Depends(get_current_user)) -> Payment:
    """
    Record a Payment
    """
    return await service.create_payment(id, body, db)


@router.put(
    '/student/{id}/payment/{payment_id}', response_model=Payment, tags=['Payments']
)
async def put_student_id_payment_payment_id(
    id: int, payment_id: int = ..., body: PaymentCreate = ..., db=Depends(get_db), user = Depends(get_current_user)
) -> Payment:
    """
    Correct a Payment (supersede)
    """
    return await service.correct_payment(id, payment_id, body, db)


@router.delete(
    '/student/{id}/payment/{payment_id}', response_model=None, tags=['Payments']
)
async def delete_student_id_payment_payment_id(id: int, payment_id: int = ..., db=Depends(get_db), user = Depends(get_current_user)) -> None:
    """
    Delete a Payment (hard delete)
    """
    await service.delete_payment(payment_id, db)


@router.get(
    '/student/{id}/paymentList', response_model=list[Payment], tags=['Payments']
)
async def get_student_id_payment_list(id: int, db=Depends(get_db), user = Depends(get_current_user)) -> list[Payment]:
    """
    Get Payment History for a Student
    """
    return await service.get_payment_history(id, db)

