# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-06-30T16:24:15+00:00

from __future__ import annotations

from typing import List

from app.core.db import get_db
from app.features.courses import service
from app.features.courses.model import Course, CourseCreate
from fastapi import APIRouter, Depends

print("Loading courses router")

router = APIRouter(tags=['Courses'])


@router.post('/course', response_model=Course, tags=['Courses'])
async def post_course(body: CourseCreate, db=Depends(get_db)) -> Course:
    """
    Create Course
    """
    return await service.create_course(body, db)


@router.put('/course/{id}', response_model=Course, tags=['Courses'])
async def put_course_id(id: int, body: CourseCreate = ..., db=Depends(get_db)) -> Course:
    """
    Update Course
    """
    return await service.update_course(id, body, db)


@router.delete('/course/{id}', response_model=None, tags=['Courses'])
async def delete_course_id(id: int, db=Depends(get_db)) -> None:
    """
    Delete Course
    """
    await service.delete_course(id, db)


@router.get('/courseList', response_model=List[Course], tags=['Courses'])
async def get_course_list(db=Depends(get_db)) -> List[Course]:
    """
    Get list of all courses
    """
    return await service.get_all_courses(db)


print("Routes:", router.routes)