# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-06-30T16:24:15+00:00

from __future__ import annotations

from uuid import UUID

from app.core.db import get_db
from app.features.users import service
from app.features.users.model import User, UserCreate
from fastapi import APIRouter, Depends

router = APIRouter(tags=['Users'])


@router.post('/user', response_model=User, tags=['Users'])
async def post_user(body: UserCreate, user_id: UUID, db=Depends(get_db)) -> User:
    """
    Create/Sync User Profile + Resolve Role
    """
    return await service.create_user(body, user_id, db)


@router.get('/user/{id}', response_model=User, tags=['Users'])
async def get_user_id(id: UUID, db=Depends(get_db)) -> User:
    """
    Get User By ID
    """
    return await service.get_user(id, db)
